POST http://localhost:3003/api/blogs/
content-type: application/json

{
    "title": "interesting",
    "author": "me",
    "url": "http://arandomhopefullynotactuallyusedurl.com",
    "likes": 3
}

###
GET http://localhost:3003/api/blogs/


###
GET http://localhost:3003/api/blogs/